# -*- coding: utf-8 -*-
"""DRUGRIPOUT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bnbLLUfcoRTlzhpQqnqAu6Ef8pJQYMWA
"""

s!python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
# Install paddle OCR
!pip install paddleocr
# Clone paddle OCR repo - get FONTS for visualization
!git clone https://github.com/PaddlePaddle/PaddleOCR

from paddleocr import PaddleOCR, draw_ocr # main OCR dependencies
import cv2 #opencv
import os # folder directory navigation

# Setup model for OCR
ocr_model = PaddleOCR(lang='en')
img_path = os.path.join('.','DRUG.png')
result = ocr_model.ocr(img_path)
result

def flatten_list(nested_list):
    flattened_list = []
    for item in nested_list:
        if isinstance(item, list):
            flattened_list.extend(flatten_list(item))
        else:
            flattened_list.append(item)
    return flattened_list

#nested list
nested_list = [result]

# nested list ot list
flattened_list = flatten_list(nested_list)
# print(flattened_list)

# Convert list to string
my_string = str(flattened_list)
# print(my_string)

# Only the text is given as a context for the model input  using "regex"

import re
text = my_string
context = re.findall(r"\('(.*?)', [0-9.]+\)", text)
context = " ".join(context)
print(context)



import transformers
from transformers import pipeline

# Load pre-trained BERT QA model
model_name = "bert-large-uncased-whole-word-masking-finetuned-squad"
qa_pipeline = pipeline("question-answering", model=model_name)


# Define multiple questions
questions = [
    "what is the name of the tablets ?",
    "What is the age of the patient ?
]


# Iterate through questions and get extracted spans
for question in questions:
    res = qa_pipeline({'context': context, 'question': question})
    print(f"Question: {question}")
    print(f"Extracted Answer: {res['answer']}\n")
